menubar: false
toolbar:
  - image | link | bullist numlist | media
plugins:
  - image
  - link
  - lists
  - media
extended_valid_elements : "iframe[src|frameborder|style|scrolling|class|width|height|name|align]"